encoding: utf-8
markdown: redcarpet
baseurl: /3d
url: metamaquina.github.io/3d/
permalink: /:title/
ga_tracking_code: 
disqus_shortname: metamaquina
prose:
  media: /img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "course_page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "hidden"
          value: "content"
